services:
  - type: web
    name: nuit-spring
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/nuit-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
